export const paths = { dictionary: "modules/pf2e-es/translation/es/dictionary.json" };
export const iconList = {
    item: "modules/pf2e-es/static/icons/item.webp",
    location: "modules/pf2e-es/static/icons/location.webp",
    lore: "modules/pf2e-es/static/icons/lore.webp",
    monster: "modules/pf2e-es/static/icons/monster.webp",
    rule: "modules/pf2e-es/static/icons/rule.webp",
    treasure: "modules/pf2e-es/static/icons/treasure.webp",
};
export const itemBlacklist = [
    "Compendium.pf2e.spells-srd.Item.o0l57UfBm9ScEUMW",
    "Compendium.pf2e.spells-srd.Item.6dDtGIUerazSHIOu",
];
export const mappings = {
    choice: { label: "label" },
    heightening: { target: "target.value" },
    item: {
        name: "name",
        badges: "system.badge.labels",
        consumableSpellName: "system.spell.name",
        consumableSpellDescription: "system.spell.system.description.value",
        consumableSpellDuration: {
            path: "system.spell.system.duration.value",
            converter: "translateDuration",
        },
        consumableSpellRange: { path: "system.spell.system.range.value", converter: "translateRange" },
        consumableSpellRequirements: "system.spell.system.requirements",
        consumableSpellTarget: "system.spell.system.target.value",
        consumableSpellTime: { path: "system.spell.system.time.value", converter: "translateTime" },
        cost: "system.cost.value",
        description: "system.description.value",
        duration: { path: "system.duration.value", converter: "translateDuration" },
        gmNote: "system.description.gm",
        heightening: { path: "system.heightening.levels", converter: "translateHeightening" },
        materials: "system.materials.value",
        prerequisites: { path: "system.prerequisites.value", converter: "translatePrerequisites" },
        primarycheck: "system.ritual.primary.check",
        range: { path: "system.range.value", converter: "translateRange" },
        requirements: "system.requirements",
        rules: { path: "system.rules", converter: "translateRules" },
        secondarycaster: "system.ritual.secondary.casters",
        secondarycheck: "system.ritual.secondary.checks",
        selfEffect: "system.selfEffect.name",
        source: { path: "system.source.value", converter: "translateSource" },
        spellVariants: { path: "system.overlays", converter: "translateSpellVariant" },
        target: "system.target.value",
        time: { path: "system.time.value", converter: "translateTime" },
        trainedLore: "system.trainedSkills.lore",
        unidentifiedName: "system.identification.unidentified.name",
        unidentifiedDescription: "system.identification.unidentified.data.description.value",
    },
    skillSpecial: { label: "label" },
    tile: { texture: "texture.src" },
    adventureActor: {
        name: "name",
        acDetails: "system.attributes.ac.details",
        blurb: "system.details.blurb",
        compendiumSource: "_stats.compendiumSource",
        sourceId: "flags.core.sourceId",
        tokenName: { path: "prototypeToken.name", converter: "translateTokenName" },
        items: { path: "items", converter: "translateAdventureActorItems" },
    },
    adventureJournal: {
        name: "name",
        pages: { path: "pages", converter: "translateAdventureJournalPages" },
    },
    adventureJournalPage: { name: "name", caption: "image.caption", text: "text.content" },
    adventureScene: {
        name: "name",
        background: "background.src",
        drawings: { path: "drawings", converter: "textCollection" },
        notes: { path: "notes", converter: "textCollection" },
        tiles: { path: "tiles", converter: "translateTiles" },
        tokens: { path: "tokens", converter: "translateTokens" },
    },
    adventureTable: {
        name: "name",
        description: "description",
        results: { path: "results", converter: "translateTableResults" },
    },
    rule: { label: "label", prompt: "prompt", text: "text" },
    tableResult: { name: "name", description: "description", text: "text" },
    token: {
        name: "name",
        items: { path: "delta.items", converter: "translateActorItems" },
    },
    value: { text: "text" },
};
