name: Auto merge Crowdin PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto --body "Auto merge desde Crowdin"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
